FROM nikolaik/python-nodejs:python3.10-nodejs20

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install dependencies
RUN npm install

COPY server-dev.ts ./
COPY tsconfig.json ./
COPY model.gcode ./

# Expose the port that the server will listen on
EXPOSE 3000

# Start the server
CMD ["npm", "run", "dev"]
